#!/usr/bin/env bash

set -e

elasticsearch-keystore add --force s3.client.default.access_key
elasticsearch-keystore add --force s3.client.default.secret_key
elasticsearch-keystore add --force s3.client.default.session_token

curl -X POST "http://localhost:9200/_nodes/reload_secure_settings?pretty"
